### ISSUE TITLE
gnome-session: conky: unknown variable '$'

### ISSUE THREAD

**Issue by ChrisLauinger77** [IuryAlves/dotfiles#1]
Hi,

my log is spammed with this message:
gnome-session[1628]: conky: unknown variable '$'

I use the beautiful Dark 4 cores conky (with the rings)

How can I get rid of the error messages ?

greets

**Comment by deragon** [comment]
Same problem here.  How can one find out the faulty line/string?

**Comment by IuryAlves** [comment]
@hustler77 , @deragon  Sorry for the wait.

What shell are you using?
How are you starting conky? Are you running through a `.sh` file, like [this](https://github.com/IuryAlves/dotfiles/blob/master/.conky/startconky.sh)?

Please, paste the `.conkyrc` file here.

I tried to reproduce this problem with the `.conkyrc` from Dark 4 Cores, but i had no luck.

**Comment by deragon** [comment]
I just realized that this repository is about a conky configuration, not conky itself.  I have the same problem, but with code that has nothing to do with this repository.  I do not think it is relevant for me to continue here; I will post my problem elsewhere.

**Comment by IuryAlves** [comment]
Yep. It's my dotfiles = ) 

Anyway i will keep this issue open, in case of someone had trouble with something.

**Comment by ChrisLauinger77** [comment]
Hi,

thanks for the answer:

here is my concyrc:
https://dl.dropboxusercontent.com/u/44733397/conkyrc

I start using
conky -c "/home/christian/conky-manager/themes/Conky Dark 4 cores/config/conkyrc" &

Greets

**Comment by sumedhe** [comment]
Delete this block in "~/.lua/scripts/haunted.lua".
The problem was solved for me! :) :)
![screenshot from 2016-10-18 02 12 01](https://cloud.githubusercontent.com/assets/2020370/19454859/60f665b6-94d8-11e6-928d-cc484ca28468.png)
